version: "3.8"

services:
  db:                       
    image: postgres:15
    restart: unless-stopped
    container_name: postgres
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/postgresql/data
    networks: [internal]

  grimoire:
    build: .
    container_name: grimoire
    image: tinyboar/pocket-grimoire:latest
    container_name: grimoire
    restart: unless-stopped
    environment:
      APP_SECRET: "ChangeMe"
      DATABASE_URL: "postgresql://symfony:symfony@db:5432/app?serverVersion=15"
    depends_on:
      - db
    networks:
      - internal

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - grimoire
    restart: unless-stopped
    networks:
      - internal

volumes:
  db_data:

networks:
  internal:
    driver: bridge
