<?php

namespace Container7f1lcTY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_STUrviZService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.STUrviZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.STUrviZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'roleRepo' => ['privates', 'App\\Repository\\RoleRepository', 'getRoleRepositoryService', true],
            'teamRepo' => ['privates', 'App\\Repository\\TeamRepository', 'getTeamRepositoryService', true],
            'translator' => ['services', 'translator', 'getTranslatorService', true],
        ], [
            'roleRepo' => 'App\\Repository\\RoleRepository',
            'teamRepo' => 'App\\Repository\\TeamRepository',
            'translator' => '?',
        ]);
    }
}
