<?php

namespace Container7f1lcTY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Kdjf4UcService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.kdjf4Uc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kdjf4Uc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'gameModel' => ['privates', 'App\\Model\\GameModel', 'getGameModelService', true],
        ], [
            'gameModel' => 'App\\Model\\GameModel',
        ]);
    }
}
