<?php

namespace Container7f1lcTY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDataControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\DataController' shared autowired service.
     *
     * @return \App\Controller\DataController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\DataController'] = $instance = new \App\Controller\DataController(($container->privates['App\\Repository\\RoleRepository'] ?? $container->load('getRoleRepositoryService')), ($container->privates['App\\Repository\\JinxRepository'] ?? $container->load('getJinxRepositoryService')), ($container->privates['App\\Model\\GameModel'] ?? ($container->privates['App\\Model\\GameModel'] = new \App\Model\GameModel((\dirname(__DIR__, 4).'/config'), 'game.yaml'))));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\DataController', $container));

        return $instance;
    }
}
