<?php

namespace Container7f1lcTY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGameModelService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Model\GameModel' shared autowired service.
     *
     * @return \App\Model\GameModel
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Model\\GameModel'] = new \App\Model\GameModel((\dirname(__DIR__, 4).'/config'), 'game.yaml');
    }
}
