<?php

namespace Container7f1lcTY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomebrewRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\HomebrewRepository' shared autowired service.
     *
     * @return \App\Repository\HomebrewRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\HomebrewRepository'] = new \App\Repository\HomebrewRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
