<?php

namespace Container7f1lcTY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\ImportCommand' shared autowired service.
     *
     * @return \App\Command\ImportCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\ImportCommand'] = $instance = new \App\Command\ImportCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\TeamRepository'] ?? $container->load('getTeamRepositoryService')), ($container->privates['App\\Repository\\RoleRepository'] ?? $container->load('getRoleRepositoryService')), ($container->privates['App\\Repository\\EditionRepository'] ?? $container->load('getEditionRepositoryService')), ($container->privates['App\\Repository\\JinxRepository'] ?? $container->load('getJinxRepositoryService')), ($container->privates['App\\Model\\LocaleModel'] ?? ($container->privates['App\\Model\\LocaleModel'] = new \App\Model\LocaleModel((\dirname(__DIR__, 4).'/config'), 'locales.yaml'))));

        $instance->setName('pocket-grimoire:import');

        return $instance;
    }
}
