<?php

namespace Container7f1lcTY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJinxRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\JinxRepository' shared autowired service.
     *
     * @return \App\Repository\JinxRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\JinxRepository'] = new \App\Repository\JinxRepository(($container->services['doctrine'] ?? $container->getDoctrineService()), ($container->privates['App\\Repository\\RoleRepository'] ?? $container->load('getRoleRepositoryService')));
    }
}
