<?php

namespace Container7f1lcTY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderRolesCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\OrderRolesCommand' shared autowired service.
     *
     * @return \App\Command\OrderRolesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\OrderRolesCommand'] = $instance = new \App\Command\OrderRolesCommand(($container->privates['App\\Repository\\RoleRepository'] ?? $container->load('getRoleRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setName('pocket-grimoire:order-roles');

        return $instance;
    }
}
