<?php

namespace Container7f1lcTY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPopulateEditionsCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\PopulateEditionsCommand' shared autowired service.
     *
     * @return \App\Command\PopulateEditionsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\PopulateEditionsCommand'] = $instance = new \App\Command\PopulateEditionsCommand(($container->privates['App\\Repository\\EditionRepository'] ?? $container->load('getEditionRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setName('pocket-grimoire:populate-editions');

        return $instance;
    }
}
