<?php

namespace Container7f1lcTY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPopulateRolesCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\PopulateRolesCommand' shared autowired service.
     *
     * @return \App\Command\PopulateRolesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\PopulateRolesCommand'] = $instance = new \App\Command\PopulateRolesCommand(($container->privates['App\\Repository\\RoleRepository'] ?? $container->load('getRoleRepositoryService')), ($container->privates['App\\Repository\\EditionRepository'] ?? $container->load('getEditionRepositoryService')), ($container->privates['App\\Repository\\TeamRepository'] ?? $container->load('getTeamRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setName('pocket-grimoire:populate-roles');

        return $instance;
    }
}
