<?php

namespace Container7f1lcTY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoleRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\RoleRepository' shared autowired service.
     *
     * @return \App\Repository\RoleRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\RoleRepository'] = new \App\Repository\RoleRepository(($container->services['doctrine'] ?? $container->getDoctrineService()), ($container->privates['App\\Repository\\EditionRepository'] ?? $container->load('getEditionRepositoryService')), ($container->privates['App\\Repository\\TeamRepository'] ?? $container->load('getTeamRepositoryService')));
    }
}
