<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7f1lcTY\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7f1lcTY/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container7f1lcTY.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container7f1lcTY\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container7f1lcTY\App_KernelProdContainer([
    'container.build_hash' => '7f1lcTY',
    'container.build_id' => '8ac56dd7',
    'container.build_time' => 1753641167,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7f1lcTY');
