<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__Jinx__CLASSMETADATA__' => 0,
'App__Entity__Team__CLASSMETADATA__' => 1,
'App__Entity__Edition__CLASSMETADATA__' => 2,
'App__Entity__Role__CLASSMETADATA__' => 3,
'App__Entity__Homebrew__CLASSMETADATA__' => 4,
'Gedmo__Translatable__Entity__MappedSuperclass__AbstractPersonalTranslation__CLASSMETADATA__' => 5,
'Gedmo__Translatable__Entity__MappedSuperclass__AbstractTranslation__CLASSMETADATA__' => 6,
'Gedmo__Translatable__Entity__Translation__CLASSMETADATA__' => 7,

], [

0 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Jinx',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Jinx',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\JinxRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'reason' => [
                            'fieldName' => 'reason',
                            'type' => 'text',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'options' => [
                                'default' => '',
                            ],
                            'columnName' => 'reason',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'reason' => 'reason',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'reason' => 'reason',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'jinxes',
                    ],
                ],
                'associationMappings' => [
                    [
                        'target' => [
                            'fieldName' => 'target',
                            'joinColumns' => [
                                [
                                    'name' => 'target_id',
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => 'jinxes',
                            'targetEntity' => 'App\\Entity\\Role',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\Jinx',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'target_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'target_id' => 'target_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'target_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                        'trick' => [
                            'fieldName' => 'trick',
                            'joinColumns' => [
                                [
                                    'name' => 'trick_id',
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => 'tricks',
                            'targetEntity' => 'App\\Entity\\Role',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\Jinx',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'trick_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'trick_id' => 'trick_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'trick_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'jinxes_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'jinxes_id_seq',
            ],
        ]
    );
},
1 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Team',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Team',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\TeamRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'identifier' => [
                            'fieldName' => 'identifier',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'identifier',
                        ],
                        'name' => [
                            'fieldName' => 'name',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'name',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'identifier' => 'identifier',
                        'name' => 'name',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'identifier' => 'identifier',
                        'name' => 'name',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'teams',
                        'indexes' => [
                            'teams_identifier_idx' => [
                                'columns' => [
                                    'identifier',
                                ],
                            ],
                        ],
                    ],
                ],
                'associationMappings' => [
                    [
                        'roles' => [
                            'fieldName' => 'roles',
                            'mappedBy' => 'team',
                            'targetEntity' => 'App\\Entity\\Role',
                            'cascade' => [],
                            'orphanRemoval' => false,
                            'fetch' => 2,
                            'type' => 4,
                            'inversedBy' => null,
                            'isOwningSide' => false,
                            'sourceEntity' => 'App\\Entity\\Team',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'teams_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'teams_id_seq',
            ],
        ]
    );
},
2 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Edition',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Edition',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\EditionRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'identifier' => [
                            'fieldName' => 'identifier',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'identifier',
                        ],
                        'name' => [
                            'fieldName' => 'name',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'name',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'identifier' => 'identifier',
                        'name' => 'name',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'identifier' => 'identifier',
                        'name' => 'name',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'editions',
                        'indexes' => [
                            'editions_identifier_idx' => [
                                'columns' => [
                                    'identifier',
                                ],
                            ],
                        ],
                    ],
                ],
                'associationMappings' => [
                    [
                        'roles' => [
                            'fieldName' => 'roles',
                            'mappedBy' => 'edition',
                            'targetEntity' => 'App\\Entity\\Role',
                            'cascade' => [],
                            'orphanRemoval' => false,
                            'fetch' => 2,
                            'type' => 4,
                            'inversedBy' => null,
                            'isOwningSide' => false,
                            'sourceEntity' => 'App\\Entity\\Edition',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'editions_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'editions_id_seq',
            ],
        ]
    );
},
3 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Role',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Role',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\RoleRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'identifier' => [
                            'fieldName' => 'identifier',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'identifier',
                        ],
                        'name' => [
                            'fieldName' => 'name',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'options' => [
                                'default' => '',
                            ],
                            'columnName' => 'name',
                        ],
                        'firstNight' => [
                            'fieldName' => 'firstNight',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'options' => [
                                'default' => 0,
                            ],
                            'columnName' => 'first_night',
                        ],
                        'firstNightReminder' => [
                            'fieldName' => 'firstNightReminder',
                            'type' => 'text',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'options' => [
                                'default' => '',
                            ],
                            'columnName' => 'first_night_reminder',
                        ],
                        'otherNight' => [
                            'fieldName' => 'otherNight',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'options' => [
                                'default' => 0,
                            ],
                            'columnName' => 'other_night',
                        ],
                        'otherNightReminder' => [
                            'fieldName' => 'otherNightReminder',
                            'type' => 'text',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'options' => [
                                'default' => '',
                            ],
                            'columnName' => 'other_night_reminder',
                        ],
                        'reminders' => [
                            'fieldName' => 'reminders',
                            'type' => 'array',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'reminders',
                        ],
                        'remindersGlobal' => [
                            'fieldName' => 'remindersGlobal',
                            'type' => 'array',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'reminders_global',
                        ],
                        'setup' => [
                            'fieldName' => 'setup',
                            'type' => 'boolean',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'options' => [
                                'default' => false,
                            ],
                            'columnName' => 'setup',
                        ],
                        'ability' => [
                            'fieldName' => 'ability',
                            'type' => 'text',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'options' => [
                                'default' => '',
                            ],
                            'columnName' => 'ability',
                        ],
                        'image' => [
                            'fieldName' => 'image',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'options' => [
                                'default' => '',
                            ],
                            'columnName' => 'image',
                        ],
                        'special' => [
                            'fieldName' => 'special',
                            'type' => 'json',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'special',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'identifier' => 'identifier',
                        'name' => 'name',
                        'first_night' => 'firstNight',
                        'first_night_reminder' => 'firstNightReminder',
                        'other_night' => 'otherNight',
                        'other_night_reminder' => 'otherNightReminder',
                        'reminders' => 'reminders',
                        'reminders_global' => 'remindersGlobal',
                        'setup' => 'setup',
                        'ability' => 'ability',
                        'image' => 'image',
                        'special' => 'special',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'identifier' => 'identifier',
                        'name' => 'name',
                        'firstNight' => 'first_night',
                        'firstNightReminder' => 'first_night_reminder',
                        'otherNight' => 'other_night',
                        'otherNightReminder' => 'other_night_reminder',
                        'reminders' => 'reminders',
                        'remindersGlobal' => 'reminders_global',
                        'setup' => 'setup',
                        'ability' => 'ability',
                        'image' => 'image',
                        'special' => 'special',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'roles',
                        'indexes' => [
                            'roles_identifier_idx' => [
                                'columns' => [
                                    'identifier',
                                ],
                            ],
                        ],
                    ],
                ],
                'associationMappings' => [
                    [
                        'edition' => [
                            'fieldName' => 'edition',
                            'joinColumns' => [
                                [
                                    'name' => 'edition_id',
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => 'roles',
                            'targetEntity' => 'App\\Entity\\Edition',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\Role',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'edition_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'edition_id' => 'edition_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'edition_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                        'team' => [
                            'fieldName' => 'team',
                            'joinColumns' => [
                                [
                                    'name' => 'team_id',
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => 'roles',
                            'targetEntity' => 'App\\Entity\\Team',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\Role',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'team_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'team_id' => 'team_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'team_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                        'jinxes' => [
                            'fieldName' => 'jinxes',
                            'mappedBy' => 'target',
                            'targetEntity' => 'App\\Entity\\Jinx',
                            'cascade' => [],
                            'orphanRemoval' => false,
                            'fetch' => 2,
                            'type' => 4,
                            'inversedBy' => null,
                            'isOwningSide' => false,
                            'sourceEntity' => 'App\\Entity\\Role',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                        ],
                        'tricks' => [
                            'fieldName' => 'tricks',
                            'mappedBy' => 'trick',
                            'targetEntity' => 'App\\Entity\\Jinx',
                            'cascade' => [],
                            'orphanRemoval' => false,
                            'fetch' => 2,
                            'type' => 4,
                            'inversedBy' => null,
                            'isOwningSide' => false,
                            'sourceEntity' => 'App\\Entity\\Role',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'roles_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'roles_id_seq',
            ],
        ]
    );
},
4 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Homebrew',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Homebrew',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\HomebrewRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'uuid' => [
                            'fieldName' => 'uuid',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'uuid',
                        ],
                        'created' => [
                            'fieldName' => 'created',
                            'type' => 'datetime',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'created',
                        ],
                        'accessed' => [
                            'fieldName' => 'accessed',
                            'type' => 'datetime',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'accessed',
                        ],
                        'json' => [
                            'fieldName' => 'json',
                            'type' => 'json',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'json',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'uuid' => 'uuid',
                        'created' => 'created',
                        'accessed' => 'accessed',
                        'json' => 'json',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'uuid' => 'uuid',
                        'created' => 'created',
                        'accessed' => 'accessed',
                        'json' => 'json',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'homebrew',
                        'indexes' => [
                            'uuid_idx' => [
                                'columns' => [
                                    'uuid',
                                ],
                            ],
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'homebrew_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'homebrew_id_seq',
            ],
        ]
    );
},
5 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Gedmo\\Translatable\\Entity\\MappedSuperclass\\AbstractPersonalTranslation',
                ],
                'namespace' => [
                    'Gedmo\\Translatable\\Entity\\MappedSuperclass',
                ],
                'rootEntityName' => [
                    'Gedmo\\Translatable\\Entity\\MappedSuperclass\\AbstractPersonalTranslation',
                ],
                'isMappedSuperclass' => [
                    true,
                ],
                'table' => [
                    [
                        'name' => 'abstract_personal_translation',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
6 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Gedmo\\Translatable\\Entity\\MappedSuperclass\\AbstractTranslation',
                ],
                'namespace' => [
                    'Gedmo\\Translatable\\Entity\\MappedSuperclass',
                ],
                'rootEntityName' => [
                    'Gedmo\\Translatable\\Entity\\MappedSuperclass\\AbstractTranslation',
                ],
                'isMappedSuperclass' => [
                    true,
                ],
                'table' => [
                    [
                        'name' => 'abstract_translation',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
7 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Gedmo\\Translatable\\Entity\\Translation',
                ],
                'namespace' => [
                    'Gedmo\\Translatable\\Entity',
                ],
                'rootEntityName' => [
                    'Gedmo\\Translatable\\Entity\\Translation',
                ],
                'customRepositoryClassName' => [
                    'Gedmo\\Translatable\\Entity\\Repository\\TranslationRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'locale' => [
                            'fieldName' => 'locale',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 8,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'locale',
                        ],
                        'objectClass' => [
                            'fieldName' => 'objectClass',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 191,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'object_class',
                        ],
                        'field' => [
                            'fieldName' => 'field',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 32,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'field',
                        ],
                        'foreignKey' => [
                            'fieldName' => 'foreignKey',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 64,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'foreign_key',
                        ],
                        'content' => [
                            'fieldName' => 'content',
                            'type' => 'text',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => null,
                            'columnName' => 'content',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'locale' => 'locale',
                        'object_class' => 'objectClass',
                        'field' => 'field',
                        'foreign_key' => 'foreignKey',
                        'content' => 'content',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'locale' => 'locale',
                        'objectClass' => 'object_class',
                        'field' => 'field',
                        'foreignKey' => 'foreign_key',
                        'content' => 'content',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'ext_translations',
                        'indexes' => [
                            'translations_lookup_idx' => [
                                'columns' => [
                                    'locale',
                                    'object_class',
                                    'foreign_key',
                                ],
                            ],
                            'general_translations_lookup_idx' => [
                                'columns' => [
                                    'object_class',
                                    'foreign_key',
                                ],
                            ],
                        ],
                        'uniqueConstraints' => [
                            'lookup_unique_idx' => [
                                'columns' => [
                                    'locale',
                                    'object_class',
                                    'field',
                                    'foreign_key',
                                ],
                            ],
                        ],
                        'options' => [
                            'row_format' => 'DYNAMIC',
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
            'Doctrine\\ORM\\Id\\IdentityGenerator' => [
                'sequenceName' => [
                    1 => 'ext_translations_id_seq',
                ],
            ],
        ],
        $o[0],
        []
    );
},

]];
